## Case 1

In [1]:
import sys
sys.path.append('C:\\Users\\INDIA\\Rahul_work\\functions')
import pandas as pd
from datetime import datetime
from stock_data import fetch_stock_data
from determine_entry_point import process_stock_data
from tvDatafeed import TvDatafeed,Interval
import time
import math

In [7]:
def fetch_case1_satisfied_symbols(symbols_path, retry_delay=1):
    symbols = pd.read_csv(symbols_path)

    satisfied_case1_symbols = pd.DataFrame(columns=['symbol', 'price_at_scan', 'high', 'low', 'volume_at_scan', 'avg_31_day_vol'])
    
    for symbol in symbols.symbol:
        data = None

        while data is None or data.empty:
            try:
                data = fetch_stock_data(symbol, interval=Interval.in_daily, n_bars=31)               
                if data is None:
                    raise ValueError("Fetched data is None")
            except Exception as e:
                print(f"Error fetching data for {symbol}: {e}")
                time.sleep(retry_delay)
                continue
                
        avg_1_month_vol = data['volume'].iloc[:len(data['volume']) - 1].mean()  # Calculating 1 month avg Volume
        day_vol = data.iloc[-1]['volume'] # Current day's Volume
        today_open = data.iloc[-1]['open']
        today_close = data.iloc[-1].close
        today_vol = data.iloc[-1].volume
        
        if today_close > 5000:
            continue
        
        if avg_1_month_vol < day_vol:  # Checks if current day's Vol. is greater than 1 month avg Vol.
            if today_open < today_close:
                transaction_type = 'BUY'
            else:
                transaction_type = 'SELL'
                
            new_row = pd.DataFrame({
                        'symbol': [symbol], 
                        'price_at_scan': [today_close],
                        'high': [data.iloc[-1].high],
                        'low': [data.iloc[-1].low],
                        'volume_at_scan': [today_vol],
                        'avg_31_day_vol': [round(avg_1_month_vol)],
                        'type': [transaction_type]                        
                    })
            satisfied_case1_symbols = pd.concat([satisfied_case1_symbols, new_row], ignore_index=True)

    return satisfied_case1_symbols

In [8]:
symbols_path = "Preparing data/symbols.csv"
satisfied_case1_symbols = fetch_case1_satisfied_symbols(symbols_path)

In [9]:
satisfied_case1_symbols

,symbol,price_at_scan,high,low,volume_at_scan,avg_31_day_vol,type
0,ASIANPAINT,2912.80000,2927.00000,2886.20000,1476148.0,1459509,BUY
1,AXISBANK,1239.25000,1267.35000,1226.65000,10344860.0,9792614,SELL
2,BAJAJFINSV,1579.25000,1611.90000,1562.00000,3675430.0,1644724,SELL
3,BPCL,314.95001,315.85001,304.85001,16934157.0,15212023,BUY
4,CIPLA,1503.50000,1511.30000,1485.00000,2266300.0,1636983,BUY
5,GRASIM,2806.89990,2830.00000,2775.00000,2880833.0,1091054,SELL
6,HDFCBANK,1604.05000,1621.00000,1588.05000,30864103.0,22805395,SELL
7,HDFCLIFE,672.79999,675.00000,639.29999,12377638.0,5711263,BUY
8,HINDUNILVR,2717.05000,2757.45000,2675.10010,3611927.0,2152162,SELL
9,ICICIBANK,1223.00000,1233.65000,1202.05000,20122521.0,16941605,SELL
10,INDUSINDBK,1396.65000,1412.50000,1386.40000,5553500.0,3939986,SELL
11,ITC,494.04999,510.64999,490.64999,42073323.0,16668430,SELL
12,KOTAKBANK,1746.20000,1780.90000,1729.05000,7487207.0,6549897,SELL
13,LT,3519.45000,3557.95000,3501.00000,3184060.0,2816171,SELL
14,NESTLEIND,2541.39990,2581.00000,2518.70000,1311044.0,697197,SELL
15,NTPC,392.60001,395.00000,381.70001,36868466.0,17107218,BUY
16,ONGC,319.54999,325.75000,312.10001,28259305.0,24174983,BUY
17,SBILIFE,1632.95000,1650.00000,1579.65000,2099093.0,1314607,BUY
18,SBIN,852.00000,868.00000,847.20001,19624845.0,16870219,SELL
19,SUNPHARMA,1619.45000,1624.95000,1592.00000,2923358.0,1874779,BUY
20,TATACONSUM,1231.25000,1257.70000,1217.40000,3325998.0,1646183,SELL
21,TATAMOTORS,1027.70000,1034.25000,995.15002,11469098.0,10779426,BUY
22,TECHM,1533.30000,1540.00000,1473.40000,2561617.0,2138787,BUY
23,TITAN,3478.39990,3552.50000,3462.14990,3862140.0,1737893,BUY

In [10]:
process_stock_data(satisfied_case1_symbols)

,symbol,price_at_scan,high,low,volume_at_scan,avg_31_day_vol,type,entry_range
0,ASIANPAINT,2912.80000,2927.00000,2886.20000,1476148.0,1459509,BUY,2927.00000
1,AXISBANK,1239.25000,1267.35000,1226.65000,10344860.0,9792614,SELL,1226.65000
2,BAJAJFINSV,1579.25000,1611.90000,1562.00000,3675430.0,1644724,SELL,1550.00000
3,BPCL,314.95001,315.85001,304.85001,16934157.0,15212023,BUY,315.85001
4,CIPLA,1503.50000,1511.30000,1485.00000,2266300.0,1636983,BUY,1511.30000
5,GRASIM,2806.89990,2830.00000,2775.00000,2880833.0,1091054,SELL,2775.00000
6,HDFCBANK,1604.05000,1621.00000,1588.05000,30864103.0,22805395,SELL,1588.05000
7,HDFCLIFE,672.79999,675.00000,639.29999,12377638.0,5711263,BUY,675.00000
8,HINDUNILVR,2717.05000,2757.45000,2675.10010,3611927.0,2152162,SELL,2675.10010
9,ICICIBANK,1223.00000,1233.65000,1202.05000,20122521.0,16941605,SELL,1200.00000
10,INDUSINDBK,1396.65000,1412.50000,1386.40000,5553500.0,3939986,SELL,1386.40000
11,ITC,494.04999,510.64999,490.64999,42073323.0,16668430,SELL,490.00000
12,KOTAKBANK,1746.20000,1780.90000,1729.05000,7487207.0,6549897,SELL,1729.05000
13,LT,3519.45000,3557.95000,3501.00000,3184060.0,2816171,SELL,3500.00000
14,NESTLEIND,2541.39990,2581.00000,2518.70000,1311044.0,697197,SELL,2500.00000
15,NTPC,392.60001,395.00000,381.70001,36868466.0,17107218,BUY,395.00000
16,ONGC,319.54999,325.75000,312.10001,28259305.0,24174983,BUY,325.75000
17,SBILIFE,1632.95000,1650.00000,1579.65000,2099093.0,1314607,BUY,1650.00000
18,SBIN,852.00000,868.00000,847.20001,19624845.0,16870219,SELL,847.20001
19,SUNPHARMA,1619.45000,1624.95000,1592.00000,2923358.0,1874779,BUY,1624.95000
20,TATACONSUM,1231.25000,1257.70000,1217.40000,3325998.0,1646183,SELL,1217.40000
21,TATAMOTORS,1027.70000,1034.25000,995.15002,11469098.0,10779426,BUY,1034.25000
22,TECHM,1533.30000,1540.00000,1473.40000,2561617.0,2138787,BUY,1550.00000
23,TITAN,3478.39990,3552.50000,3462.14990,3862140.0,1737893,BUY,3552.50000

In [ ]:
satisfied_case1_symbols.to_csv('case1.csv', index=False)